# Generated by Django 5.1.2 on 2024-10-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_user_type_pharmacyprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyprofile',
            old_name='license_number',
            new_name='responsible_person',
        ),
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='certification_number',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='daily_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='gln_number',
            field=models.CharField(default=123, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='permanent_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='daily_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='first_name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='last_name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='national_id',
            field=models.CharField(default=123, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='permanent_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='phone_number',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
