# Generated by Django 5.1.2 on 2024-10-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_license_number_pharmacyprofile_responsible_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
