# Generated by Django 5.1.2 on 2024-10-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_technicianprofile_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
